[2024-05-28 11:48:53,976] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-05-28 11:48:59,484] [WARNING] [runner.py:202:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2024-05-28 11:48:59,484] [INFO] [runner.py:568:main] cmd = /home/hpc/b207dd/b207dd11/miniconda3/envs/py38/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgMywgNCwgNSwgNiwgN119 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None llava/train_parallel_deepspeed_mixtral_adapter.py --num_stages=8
[2024-05-28 11:49:02,939] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-05-28 11:49:04,661] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]}
[2024-05-28 11:49:04,661] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=8, node_rank=0
[2024-05-28 11:49:04,661] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]})
[2024-05-28 11:49:04,661] [INFO] [launch.py:163:main] dist_world_size=8
[2024-05-28 11:49:04,661] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
[2024-05-28 11:49:04,670] [INFO] [launch.py:253:main] process 3159464 spawned with command: ['/home/hpc/b207dd/b207dd11/miniconda3/envs/py38/bin/python', '-u', 'llava/train_parallel_deepspeed_mixtral_adapter.py', '--local_rank=0', '--num_stages=8']
[2024-05-28 11:49:04,679] [INFO] [launch.py:253:main] process 3159465 spawned with command: ['/home/hpc/b207dd/b207dd11/miniconda3/envs/py38/bin/python', '-u', 'llava/train_parallel_deepspeed_mixtral_adapter.py', '--local_rank=1', '--num_stages=8']
[2024-05-28 11:49:04,694] [INFO] [launch.py:253:main] process 3159466 spawned with command: ['/home/hpc/b207dd/b207dd11/miniconda3/envs/py38/bin/python', '-u', 'llava/train_parallel_deepspeed_mixtral_adapter.py', '--local_rank=2', '--num_stages=8']
[2024-05-28 11:49:04,707] [INFO] [launch.py:253:main] process 3159467 spawned with command: ['/home/hpc/b207dd/b207dd11/miniconda3/envs/py38/bin/python', '-u', 'llava/train_parallel_deepspeed_mixtral_adapter.py', '--local_rank=3', '--num_stages=8']
/home/hpc/b207dd/b207dd11/miniconda3/envs/py38/bin/python: can't open file 'llava/train_parallel_deepspeed_mixtral_adapter.py': [Errno 2] No such file or directory
[2024-05-28 11:49:04,720] [INFO] [launch.py:253:main] process 3159469 spawned with command: ['/home/hpc/b207dd/b207dd11/miniconda3/envs/py38/bin/python', '-u', 'llava/train_parallel_deepspeed_mixtral_adapter.py', '--local_rank=4', '--num_stages=8']
/home/hpc/b207dd/b207dd11/miniconda3/envs/py38/bin/python: can't open file 'llava/train_parallel_deepspeed_mixtral_adapter.py': [Errno 2] No such file or directory
[2024-05-28 11:49:04,734] [INFO] [launch.py:253:main] process 3159470 spawned with command: ['/home/hpc/b207dd/b207dd11/miniconda3/envs/py38/bin/python', '-u', 'llava/train_parallel_deepspeed_mixtral_adapter.py', '--local_rank=5', '--num_stages=8']
/home/hpc/b207dd/b207dd11/miniconda3/envs/py38/bin/python: can't open file 'llava/train_parallel_deepspeed_mixtral_adapter.py': [Errno 2] No such file or directory
[2024-05-28 11:49:04,743] [INFO] [launch.py:253:main] process 3159471 spawned with command: ['/home/hpc/b207dd/b207dd11/miniconda3/envs/py38/bin/python', '-u', 'llava/train_parallel_deepspeed_mixtral_adapter.py', '--local_rank=6', '--num_stages=8']
/home/hpc/b207dd/b207dd11/miniconda3/envs/py38/bin/python: can't open file 'llava/train_parallel_deepspeed_mixtral_adapter.py': [Errno 2] No such file or directory
[2024-05-28 11:49:04,752] [INFO] [launch.py:253:main] process 3159472 spawned with command: ['/home/hpc/b207dd/b207dd11/miniconda3/envs/py38/bin/python', '-u', 'llava/train_parallel_deepspeed_mixtral_adapter.py', '--local_rank=7', '--num_stages=8']
[2024-05-28 11:49:04,753] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 3159464
/home/hpc/b207dd/b207dd11/miniconda3/envs/py38/bin/python: can't open file 'llava/train_parallel_deepspeed_mixtral_adapter.py': [Errno 2] No such file or directory
[2024-05-28 11:49:04,778] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 3159465
/home/hpc/b207dd/b207dd11/miniconda3/envs/py38/bin/python: can't open file 'llava/train_parallel_deepspeed_mixtral_adapter.py': [Errno 2] No such file or directory
/home/hpc/b207dd/b207dd11/miniconda3/envs/py38/bin/python: can't open file 'llava/train_parallel_deepspeed_mixtral_adapter.py': [Errno 2] No such file or directory
[2024-05-28 11:49:04,798] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 3159466
[2024-05-28 11:49:04,798] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 3159467
/home/hpc/b207dd/b207dd11/miniconda3/envs/py38/bin/python: can't open file 'llava/train_parallel_deepspeed_mixtral_adapter.py': [Errno 2] No such file or directory
[2024-05-28 11:49:04,814] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 3159469
[2024-05-28 11:49:04,827] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 3159470
[2024-05-28 11:49:04,839] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 3159471
[2024-05-28 11:49:04,851] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 3159472
[2024-05-28 11:49:04,864] [ERROR] [launch.py:322:sigkill_handler] ['/home/hpc/b207dd/b207dd11/miniconda3/envs/py38/bin/python', '-u', 'llava/train_parallel_deepspeed_mixtral_adapter.py', '--local_rank=7', '--num_stages=8'] exits with return code = 2
